# This is meant for local development only. Do not use this in production.
version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: cloud0_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloud0
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
